#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme
title: Sam Rosenberg
description: My website
theme: null
markdown: kramdown
exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
